default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432

development:
  <<: *default
  database: recipes-development
  username: postgres
  host: db

test:
  <<: *default
  database: recipes-test
  username: postgres
  host: db
