default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: dev
  password: dev

development:
  <<: *default
  database: recipes-development

test:
  <<: *default
  database: recipes-test

production:
  <<: *default
  database: recipes-prod
